# Build stage
FROM node:25-alpine AS builder

WORKDIR /app

# Create AWS credentials file
RUN --mount=type=secret,id=aws,target=/root/.aws/credentials

# Copy root package.json
COPY package.json ./

# Copy backend package.json files
COPY credit-pulse/backend/package.json ./credit-pulse/backend/

# Install dependencies for backend
RUN npm install --workspace=credit-pulse/backend

# Copy only the backend code
COPY credit-pulse/backend ./credit-pulse/backend

# Generate Prisma Client
RUN npm run prisma:generate:prod

# Build backend and frontend applications
RUN npm run build:backend

# Final stage
FROM node:25-alpine

WORKDIR /app

# Copy only what we need to run
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# Copy NestJS build output
COPY --from=builder /app/credit-pulse/backend/dist ./credit-pulse/backend/dist
COPY --from=builder /app/credit-pulse/backend/generated ./credit-pulse/backend/generated
COPY --from=builder /app/credit-pulse/backend/package.json ./credit-pulse/backend/package.json
COPY --from=builder /app/credit-pulse/backend/tsconfig.build.json ./credit-pulse/backend/tsconfig.build.json
COPY --from=builder /app/credit-pulse/backend/tsconfig.json ./credit-pulse/backend/tsconfig.json
COPY --from=builder /app/credit-pulse/backend/global-bundle.pem ./credit-pulse/backend/global-bundle.pem

# Expose NestJS backend default port
EXPOSE 3001

# Run NestJS backend
CMD ["npm", "run", "start:prod:backend"]