http:
  host: localhost
  port: 8080

db:
  postgres:
    host: localhost
    port: 5432
    username: postgres
    password: root
    database: credit-pulse

jwt:
  secret: your_jwt_secret_key
  expiresIn: 3600s
